services:
  client:
    build: 
     context: ./client
     dockerfile: Dockerfile
    env_file: ./client/.env.local
    volumes:
      - /app/node_modules
      - frontend_builds:/usr/share/nginx/html
    networks:
      multi_net:   
        aliases:
          - OCRSystem

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    ports:
      - "5005:5005"
    env_file:
      - ./server/.env
    restart: unless-stopped
    networks:
      multi_net:   
        aliases:
          - aadhaar-ocr 
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5005/api/parse"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      project: "OCRSystem"

networks:
  multi_net:
    external: true
    labels:
      project: "OCRSystem"

volumes:
  frontend_builds:
    external: true
