services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - multi_net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3005"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      project: "OCRSystem"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    ports:
      - "5005:5005"
    env_file:
      - ./server/.env
    restart: unless-stopped
    networks:
      multi_net:   
        aliases:
          - aadhaar-ocr 
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5005/api/parse"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      project: "OCRSystem"

networks:
  multi_net:
    external: true
    labels:
      project: "OCRSystem"
